import { Zcl } from "zigbee-herdsman";

const zDataTypeToHomieStringMap : Map<Zcl.DataType, string> = new Map<Zcl.DataType, string>([
    [Zcl.DataType.DATA8, 'integer'],
    [Zcl.DataType.DATA16, 'integer'],
    [Zcl.DataType.DATA24, 'integer'],
    [Zcl.DataType.DATA32, 'integer'],
    [Zcl.DataType.DATA40, 'integer'],
    [Zcl.DataType.DATA48, 'integer'],
    [Zcl.DataType.DATA56, 'integer'],
    [Zcl.DataType.DATA64, 'integer'],
    [Zcl.DataType.BITMAP8, 'integer'],
    [Zcl.DataType.BITMAP16, 'integer'],
    [Zcl.DataType.BITMAP24, 'integer'],
    [Zcl.DataType.BITMAP32, 'integer'],
    [Zcl.DataType.BITMAP40, 'integer'],
    [Zcl.DataType.BITMAP48, 'integer'],
    [Zcl.DataType.BITMAP56, 'integer'],
    [Zcl.DataType.BITMAP64, 'integer'],
    [Zcl.DataType.ENUM8, 'enum'],
    [Zcl.DataType.ENUM16, 'enum'],
    [Zcl.DataType.UINT8, 'integer'],
    [Zcl.DataType.UINT16, 'integer'],
    [Zcl.DataType.UINT24, 'integer'],
    [Zcl.DataType.UINT32, 'integer'],
    [Zcl.DataType.UINT40, 'integer'],
    [Zcl.DataType.UINT48, 'integer'],
    [Zcl.DataType.UINT56, 'integer'],
    [Zcl.DataType.UINT64, 'integer'],
    [Zcl.DataType.INT8, 'integer'],
    [Zcl.DataType.INT16, 'integer'],
    [Zcl.DataType.INT24, 'integer'],
    [Zcl.DataType.INT32, 'integer'],
    [Zcl.DataType.INT40, 'integer'],
    [Zcl.DataType.INT48, 'integer'],
    [Zcl.DataType.INT56, 'integer'],
    [Zcl.DataType.INT64, 'integer'],
    [Zcl.DataType.SEMI_PREC, 'float'],
    [Zcl.DataType.SINGLE_PREC, 'float'],
    [Zcl.DataType.DOUBLE_PREC, 'float'],
    [Zcl.DataType.BOOLEAN, 'boolean'],
    [Zcl.DataType.CHAR_STR, 'string'],
    [Zcl.DataType.OCTET_STR, 'string'],
    [Zcl.DataType.LONG_CHAR_STR, 'string'],
    [Zcl.DataType.LONG_OCTET_STR, 'string'],
]);

export function getHomieDataType(zclDataType: Zcl.DataType): string {
    return zDataTypeToHomieStringMap.get(zclDataType) || 'string';
}